### ISSUE TITLE
rc examples are broken

### ISSUE THREAD

**Issue by crumblingstatue** [jeremyletang/rust-sfml#101]
https://travis-ci.org/jeremyletang/rust-sfml/builds/63751034#L472

**Comment by jeremyletang** [comment]
hey, I've recently remove from build the rc part as i planned to refactor some stuff. In the same time @SpaceManiac have propose to change some things on the library, so there will be some breaking change for a time, but this will be fix.
The cargo version stay stable for the users I think.

**Comment by crumblingstatue** [comment]
I commented the rc example out, so the Travis build passes now.
It will need to be uncommented and updated once rc is available again.
