### ISSUE TITLE
Probable typo in function name

### ISSUE THREAD

**Issue by shepmaster** [jeremyletang/rust-sfml#110]
```rust
pub fn mew_from_bytes(byte0: u8, byte1: u8, byte2: u8, byte3: u8) -> IpAddress {
```

:cat: :cat2: :smile_cat:

**Comment by crumblingstatue** [comment]
Haha, that's funny!
I'll fix it.

**Comment by shepmaster** [comment]
Ah, I think I see the root of this problem:

![image](https://cloud.githubusercontent.com/assets/174509/10117821/a88fab26-6432-11e5-8056-6dc89f546049.png)

It's a case of cat-on-the-brain! :cat2:

**Comment by crumblingstatue** [comment]
> Ah, I think I see the root of this problem:
> 
> 
> 
> It's a case of cat-on-the-brain!

To be accurate, that function was not written by me.
