### ISSUE TITLE
Retina display resolution

### ISSUE THREAD

**Issue by paezao** [jeremyletang/rust-sfml#114]
Hey guys, do you know how to get correct retina display res with rust-sfml?

**Comment by crumblingstatue** [comment]
Does the SFML C++ API support this? If it does, then rust-sfml should support it too. If it doesn't, this issue should be taken upstream.

**Comment by paezao** [comment]
I think they only support this through plist flags...

**Comment by crumblingstatue** [comment]
> I think they only support this through plist flags...

I don't even know what that means, so I don't know what I can do about this issue.

**Comment by paezao** [comment]
Yes I think that's something they should improve.

**Comment by SeedyROM** [comment]
I am embedding an `Info.plist` into my exectuable and settings that key. To no avail... :'(
