### ISSUE TITLE
Support antialising/"smoothing" if possible

### ISSUE THREAD

**Issue by mrkgnao** [jeremyletang/rust-sfml#115]
I'm not sure if SFML itself supports this, though.

**Comment by mrkgnao** [comment]
It seems some changes might be made here:

https://github.com/jeremyletang/rust-sfml/blob/2df50cc6e028dbff9ca42752057e2be2d8ee57a9/src/window/context_settings.rs

**Comment by mrkgnao** [comment]
Or perhaps this 

https://github.com/jeremyletang/rust-sfml/blob/144b099d1edc15e0033beabe1dea348cf79d06d5/src/graphics/texture.rs#L305

is the key, in which case nothing is required.

**Comment by crumblingstatue** [comment]
Alright, #116 is now merged.
