### ISSUE TITLE
Travis buiding minor issue

### ISSUE THREAD

**Issue by Rafagd** [jeremyletang/rust-sfml#119]
It seems that someone needs to ask them to allow libcsfml (and maybe its deps) to be installed on their VMs:
https://github.com/travis-ci/apt-package-whitelist#package-approval-process

I'm reporting this because i'm copy-pasting your .travis.yml into my project.

**Comment by crumblingstatue** [comment]
Since we rely on csfml from source, we don't really have need for this.
But if you have a personal need for this, you could be the one to request this from them.
