### ISSUE TITLE
PartialEq for Color

### ISSUE THREAD

**Issue by mmstick** [jeremyletang/rust-sfml#127]
It would be great if `Color` would `PartialEq`, then [this](https://github.com/zakkor/rust-sfml-rocket/blob/master/src/main.rs#L373:L379) wouldn't happen.

**Comment by crumblingstatue** [comment]
Looks like a simple case of missing functionality.
I went ahead and derived `PartialEq`, along with a couple more useful traits in 49ad4c9ae708721005626affec11d0ddb34abac1.
