### ISSUE TITLE
Create `Key` from ASCII

### ISSUE THREAD

**Issue by suhr** [jeremyletang/rust-sfml#128]
Something like 
```rust
impl From<u8> for Key {
    ...
}
```

**Comment by crumblingstatue** [comment]
What's your use-case for this?

Also, it might not be possible to map every possible u8 value to a Key. For example, what should ASCII `4` (end of transmission) map to?

Simply converting u8 into a key also does not make it clear that we are mapping ASCII characters.
A named function would make the intent clearer.

**Comment by suhr** [comment]
> What's your use-case for this?

It allows to do something like 
```rust
b"azsxdcfvgbhnjmk,l.;/'".into_iter()
    .map(|&b| into_key(b)).zip(1..22)
```

(yep, this is a virtual midi keyboard)

> For example, what should ASCII 4 (end of transmission) map to?

`Key::Unknown`.

**Comment by crumblingstatue** [comment]
Does vanilla (C++) SFML have this feature?

We should try to stick to only implementing features existing in vanilla SFML, especially if they are something that could be implemented outside of rust-sfml.

**Comment by suhr** [comment]
Ok, let it be outside of rust-sfml.
