### ISSUE TITLE
rust-sfml doesn't link properly on Travis (Ubuntu), does so on Arch

### ISSUE THREAD

**Issue by SilverWingedSeraph** [jeremyletang/rust-sfml#129]
While I can build my project deucalion just fine on Arch, my Travis builds fail to build, despite the fact that libsfml-dev and libcsfml-dev are installed:

https://s3.amazonaws.com/archive.travis-ci.org/jobs/143740748/log.txt

I recognize that this could be an issue with my Travis config, but I don't think it is, since the required libraries _are_ installed.

**Comment by crumblingstatue** [comment]
The following looks suspicious to me:

> The following extra packages will be installed:
  libcsfml-audio1.6 libcsfml-graphics1.6 libcsfml-network1.6
  libcsfml-system1.6 libcsfml-window1.6 libglew1.5 libopenal-data libopenal1
  libsfml-audio1.6 libsfml-graphics1.6 libsfml-network1.6 libsfml-system1.6
  libsfml-window1.6 libsoil1
Suggested packages:
  glew-utils1.5 libsfml1.6-dbg libsfml-doc
The following NEW packages will be installed:
  libcsfml-audio1.6 libcsfml-dev libcsfml-graphics1.6 libcsfml-network1.6
  libcsfml-system1.6 libcsfml-window1.6 libglew1.5 libopenal-data libopenal1
  libsfml-audio1.6 libsfml-dev libsfml-graphics1.6 libsfml-network1.6
  libsfml-system1.6 libsfml-window1.6 libsoil1

Looks to me as if it was installing SFML 1.6, which is incompatible with the newer SFML 2.x versions.

**Comment by SilverWingedSeraph** [comment]
Oh, you're absolutely right. I totally missed that, sorry. Closed, as it's not your problem.

**Comment by crumblingstatue** [comment]
Also note that we [require](https://github.com/jeremyletang/rust-sfml#requirements) **specifically** SFML **2.3**.
We only support one specific SFML version at a time. We make no guarantees that rust-sfml works with any other version of SFML.

**Comment by SilverWingedSeraph** [comment]
I may end up doing that. For now, I'm pulling 2.3.2 from Proposed. Anyway, thank you.
