### ISSUE TITLE
`Text` accepts `&str` but doesn't support unicode

### ISSUE THREAD

**Issue by suhr** [jeremyletang/rust-sfml#132]
Simple test: 
```rust
let text = Text::new_init("ё", &font, 14).unwrap();
window.draw(&text);
```

It shows `ё` as two invalid characters.

See also: “[How to avoid problems with non-ASCII characters?](http://www.sfml-dev.org/tutorials/2.0/graphics-text.php#how-to-avoid-problems-with-non-ascii-characters)”

**Comment by SpaceManiac** [comment]
I opened a pull request attempting to fix this issue. Let me know if it works for you.
