### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by RUSshy** [jeremyletang/rust-sfml#156]
Hello, 

I added ``sfml = "0.11.2"``  create in my project, added the .a libs and dlls in ``C:\Users\rus\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib`` folder

Then i try to compile my project but i get: 

``.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib\csfml-system.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'``

I double checked, and redownloaded them, i'm 100% sure i picked the x64 builds

**Comment by crumblingstatue** [comment]
Have you tried using these libs you have downloaded in a C application? Does that give the same error? This might be a CSFML problem instead of a rust-sfml problem.

**Comment by RUSshy** [comment]
i was never able to build CSFML :/ is there other place than sfml website to download the files ?

**Comment by crumblingstatue** [comment]
I suggest you ask for help [here](http://en.sfml-dev.org/forums/index.php?board=12.0) on the SFML forums.

Since this is not a rust-sfml issue, I'm closing this.

**Comment by RUSshy** [comment]
oh yes you are right, im not alone :/ http://en.sfml-dev.org/forums/index.php?PHPSESSID=vrbb1kejrut985rmp4hom36da1&topic=20934.0
