### ISSUE TITLE
Get audio samples from a buffer

### ISSUE THREAD

**Issue by petoknm** [jeremyletang/rust-sfml#168]
It is nice to have a simple audio buffer. But what good is it if I cant access the samples in it? The documentation of the `sample_count` function specifies that there should be a `get_samples` function... but it sure is not present on the buffer itself.
![screenshot_20171004_193906](https://user-images.githubusercontent.com/5087675/31190614-de0d9196-a93b-11e7-9494-044bbd5a9701.png)

**Comment by petoknm** [comment]
I added a PR with an implementation of something I was looking for

**Comment by crumblingstatue** [comment]
I don't know how I overlooked this in #144.
