### ISSUE TITLE
Installing the rust-sfml. Rust 2017. Windows.

### ISSUE THREAD

**Issue by InnocentusLime** [jeremyletang/rust-sfml#174]
Compiling with gnu-stable toolchain. When I compile the project with `cargo build`, I get the following error message:

> error: linking with gcc failed: exit code: 1
...
  = note: ld: cannot find -lsfml-graphics
          ld: cannot find -lcsfml-graphics
          ld: cannot find -lsfml-window
          ld: cannot find -lcsfml-window
          ld: cannot find -lsfml-audio
          ld: cannot find -lcsfml-audio
          ld: cannot find -lsfml-system
          ld: cannot find -lcsfml-system

P.S.
The fix that was used in 2105 doesn't work since I don't have the folders mentioned in that issue:
https://github.com/jeremyletang/rust-sfml/issues/106

**Comment by InnocentusLime** [comment]
Figured out where to place them. But here shows another issue. The compiler skips the lib files naming them incompatible.

**Comment by crumblingstatue** [comment]
> The compiler skips the lib files naming them incompatible.

I don't understand what you mean by that.

**Comment by InnocentusLime** [comment]
Here's the extract from a long error message I after calling `cargo build`:

> Non-UTF-8 output: ld: skipping incompatible C:\\Users\\\xc8\xed\xed\xee\xea\xe5\xed\xf2\xe8\xe9\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib/libcsfml-graphics.a when searching for -lcsfml-graphics\r\n

**Comment by crumblingstatue** [comment]
That error message usually happens when you try to link libraries compiled for different architectures.

Are you sure both your rust and SFML are `x86_64-pc-windows-gnu`?

**Comment by InnocentusLime** [comment]
Yes, my Rust toolchain is x86_64-pc-windowsgnu and the SFML .a files claim to work with MinGW(GCC)

**Comment by crumblingstatue** [comment]
Since there has been no reply to this thread for 2 weeks, and this doesn't seem to be an issue directly with rust-sfml, I'll close this one.
