### ISSUE TITLE
Key::{name}.is_pressed() not working on OSX Sierra

### ISSUE THREAD

**Issue by tavurth** [jeremyletang/rust-sfml#176]
Hi, thanks for making this port, it seems like it's very full featured from what I've seen.

I've run into a problem running the pong demo, while I can start the game, the 

```
Key::Up.is_pressed();
Key::Down.is_pressed();
```

Functions always return false. I've tried running this from a separate thread, and from the standard pong example.

Other events like the spacebar to start, are functioning well.

Any ideas on what I could try to fix this?

```
rust-sfml@master
rustc 1.23.0-nightly (3b82e4c74 2017-11-05)
```

**Comment by tavurth** [comment]
Looks like it was a conflict with [Karabiner Elements](https://github.com/tekezo/Karabiner-Elements) Keys are now responding properly to the is_pressed function.

**Comment by tavurth** [comment]
There's a solution [here](https://github.com/tekezo/Karabiner-Elements/blob/master/appendix/eventtap/main.cpp) as referenced [here](https://github.com/tekezo/Karabiner-Elements/issues/155). 

Implementing that in Rust code is still a bit beyond me for the moment. 

You can close this issue

**Comment by crumblingstatue** [comment]
Does this issue aslo occur when using SFML directly, or only with rust-sfml?

If it's the former, then you should take this issue upstream, to https://github.com/SFML/SFML

**Comment by crumblingstatue** [comment]
Actually, I see there is already an upstream issue [here](https://github.com/SFML/SFML/issues/1217), so I'm closing this.
