### ISSUE TITLE
Way for sprite to own texture?

### ISSUE THREAD

**Issue by DaveKram** [jeremyletang/rust-sfml#180]
I'm trying to get a sprite wrapper I have written to own the texture that is provided by a path. Here is my current code:

```
use sfml::graphics::{Sprite, Texture, Transformable};
use object_manager::object;

pub struct game_sprite<'s> {
    tex: Texture,
    spr: Sprite<'s>,
    x: u32,
    y: u32
}

impl<'s> object<'s> for game_sprite<'s> {
    fn new(texture_path: &'static str, xParam: u32, yParam: u32) -> game_sprite<'s> {
        game_sprite {
            tex: Texture::from_file(texture_path).unwrap(),
            spr: Sprite::new(),
            x: xParam,
            y: yParam
        }
    }

    fn set_x(&mut self, newX: u32) {
        self.x = newX;
        self.spr.set_position((self.x as f32, self.y as f32));
    }

    fn set_y(&mut self, newY: u32) {
        self.y = newY;
        self.spr.set_position((self.x as f32, self.y as f32));
    }

    fn get_x(&self) -> u32 {
        self.x
    }

    fn get_y(&self) -> u32 {
        self.y
    }

    fn get_sprite_ref(&self) -> &Sprite<'s> {
        &self.spr
    }
}
```

I'm running into the issue of that sprite lifetime not allowing me to apply the texture with Sprite::with_texture() or something similar. I've tried creating a hashmap of Hashmap<&'static str, Texture> to load textures before I assign a texture via something like set_texture(tex: &'s Texture), but I run into lifetime issues (insert game_sprite into hash map, insert texture into different hashmap, use get_mut on game_sprite hashmap to attempt to call set_texture on that mutable reference).  

Edit: It's mostly following this issue:

`cannot infer an appropriate lifetime for autoref due to conflicting requirements`

which leads me to assume that the Texture (wherever I'm grabbing it from - HashMap, etc), can't infer the 's lifetime. 

I'm not doing something right obviously - would appreciate some ideas/help.

**Comment by crumblingstatue** [comment]
[Self-referential structs are a pain point](https://internals.rust-lang.org/t/improving-self-referential-structs/4808) in Rust right now. There are "workarounds", like the [rental](https://crates.io/crates/rental) crate, but I never tried it, so I don't know if it could help with this.

For now, I would recommend not putting a Sprite and its Texture in the same struct. Rather, have a "texture store" that outlives your sprites, and your sprites should borrow from that.

Another feature that could help is `Sprite` having support for `Rc<Texture>` in addition to `Texture`, but I haven't found a good design yet. #164 is related, it's the same feature, but for `Text`/`Font`.

**Comment by DaveKram** [comment]
Thanks for the response - new to the Rust game-dev/graphics side of things. I changed things around to have this:

```
pub struct object_manager<'s> {
    textureList: HashMap<String, Texture>,
    playerList: HashMap<String, player::player<'s>>,
    enemyList: HashMap<String, enemy::enemy<'s>>,
    itemList: HashMap<String, item::item<'s>>,
    otherSpriteList: HashMap<String, game_sprite::game_sprite<'s>>,
}
```

So I can insert a set of textures before I create any sprites. However, whenever I do something like this:

```
pub fn init(&mut self, obj_man: &mut object_manager) {
        self.mus.set_looping(true);
        self.mus.set_volume(30.0);
        self.mus.play();

        obj_man.add_texture("tex_mm_title_banner".to_owned(), Texture::from_file("assets/main_menu/title.png").unwrap());
        let texRef = obj_man.get_texture_list().get("tex_mm_title_banner").unwrap();
        obj_man.add_other_sprite("mm_title_banner".to_owned(), game_sprite::game_sprite::new(texRef, 0, 0));
    }
```

I get that error:

```
error[E0495]: cannot infer an appropriate lifetime for autoref due to conflicting requirements
  --> src\state_manager\state_main_menu.rs:25:30
   |
25 |         let texRef = obj_man.get_texture_list().get("tex_mm_title_banner").unwrap();
   |                              ^^^^^^^^^^^^^^^^
   |
note: first, the lifetime cannot outlive the anonymous lifetime #2 defined on the method body at 19:5...
  --> src\state_manager\state_main_menu.rs:19:5
   |
19 | /     pub fn init<'s>(&mut self, obj_man: &mut object_manager) {
20 | |         self.mus.set_looping(true);
21 | |         self.mus.set_volume(30.0);
22 | |         self.mus.play();
...  |
26 | |         obj_man.add_other_sprite("mm_title_banner".to_owned(), game_sprite::game_sprite::new(texRef, 0, 0));
27 | |     }
   | |_____^
note: ...so that reference does not outlive borrowed content
  --> src\state_manager\state_main_menu.rs:25:22
   |
25 |         let texRef = obj_man.get_texture_list().get("tex_mm_title_banner").unwrap();
   |                      ^^^^^^^
note: but, the lifetime must be valid for the anonymous lifetime #3 defined on the method body at 19:5...
  --> src\state_manager\state_main_menu.rs:19:5
   |
19 | /     pub fn init<'s>(&mut self, obj_man: &mut object_manager) {
20 | |         self.mus.set_looping(true);
21 | |         self.mus.set_volume(30.0);
22 | |         self.mus.play();
...  |
26 | |         obj_man.add_other_sprite("mm_title_banner".to_owned(), game_sprite::game_sprite::new(texRef, 0, 0));
27 | |     }
   | |_____^
note: ...so that types are compatible (expected &mut object_manager::object_manager<'_>, found &mut object_manager::object_manager<'_>)
  --> src\state_manager\state_main_menu.rs:26:17
   |
26 |         obj_man.add_other_sprite("mm_title_banner".to_owned(), game_sprite::game_sprite::new(texRef, 0, 0));
   |                 ^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `game`.
```

Do you think that is because the get() call from the texture hash map can't infer the 's lifetime?

**Comment by crumblingstatue** [comment]
With this new design, you still have the textures and sprites in the same struct, which brings us back to the problem of [self-referential structs](https://internals.rust-lang.org/t/improving-self-referential-structs/4808). Also, having everything in HashMaps doesn't sound very efficient.

My usual design is usually this (simplified):

```Rust
struct Resources {
    textures: Vec<Texture>,
    sound_buffers: Vec<SoundBuffer>,
   ...
}

struct GameState<'a> {
    sprites: Vec<Sprite<'a>>,
}

fn new_game() {
    let resources = Resources::new();
    let mut game_state = GameState::new(&resources);
   ...
}
```

**Comment by DaveKram** [comment]
Hmmm, thanks - I've taken a new approach to the overall design. Thanks for you help.
