### ISSUE TITLE
Figure out whether we need to link against SFML directly

### ISSUE THREAD

**Issue by crumblingstatue** [jeremyletang/rust-sfml#182]
During testing #181, I tested whether not linking against SFML would work on linux. It does work, despite my expectations.

We need to figure out why we needed to link against SFML in the first place, and if we still need to.

**Comment by crumblingstatue** [comment]
Linking against SFML was added in #151. Back then, I just accepted it without questioning it.

The submitter claims

> On my linux, also linking sfml is necessary (csfml is just a binding).

I wonder what can seemingly cause this on certain setups.

**Comment by crumblingstatue** [comment]
@juliendehos 
If possible, could you give us more information on #151? Do you know the reason why this was required on your Linux?

**Comment by juliendehos** [comment]
As far as I remember, csfml is a binding for sfml so the csfml lib doesn't include the sfml code.
That's why the csfml packages include sfml as a dependency in linux distributions (https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/csfml, http://cdn-fastly.deb.debian.org/debian/pool/main/libc/libcsfml/libcsfml_2.3-3.dsc).
However, I don't know how the csfml lib is built for windows.

**Comment by crumblingstatue** [comment]
> As far as I remember, csfml is a binding for sfml so the csfml lib doesn't include the sfml code.

That's correct, but it _does_ __link__ against SFML, as far as I'm aware. Is there a case where it doesn't?

> That's why the csfml packages include sfml as a dependency in linux distributions (https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/csfml, http://cdn-fastly.deb.debian.org/debian/pool/main/libc/libcsfml/libcsfml_2.3-3.dsc).

`sfml` is a dependency of `csfml`, just as, for example, `libsndfile` is a dependency of `sfml`. But that doesn't mean you need to link against `libsndfile` when you're linking against `sfml`, because `sfml` already links against `libsndfile`.

I tested on Arch Linux, and `rust-sfml` works without having to link against `sfml`, linking against `csfml` is sufficient. Was this different in your case when you submitted your pull request? Did you get a link error?

**Comment by juliendehos** [comment]
That sounds correct. I sent the PR #151 months ago but I don't use rust anymore and I don't remember the problem I had at that time. So you may undo this PR.

**Comment by crumblingstatue** [comment]
Alright, thanks for your help!

For now, I'll stop linking to sfml directly, and if any problem arises, we have this discussion for reference.
