### ISSUE TITLE
Lifetime issues with `Sound` and `SoundBuffer`

### ISSUE THREAD

**Issue by aszkid** [jeremyletang/rust-sfml#183]
I'm having trouble wrapping my head around the lifetime requirements of the `SoundBuffer` reference in `Sound`. Consider the following minimal example:

```
use sfml::audio::{Sound, SoundBuffer};

struct MyStruct<'t> {
   beep_buffer: SoundBuffer,
   beep: Sound<'t>
}

impl<'t> MyStruct<'t> {
   fn new() -> MyStruct<'t> {
      let mut instance = MyStruct {
         beep_buffer: SoundBuffer:from_samples(...).unwrap(),
         beep: Sound::new()
      };
      instance.beep.set_buffer(&instance.beep_buffer);
      return instance;
   }
}

fn main() {
   let test = MyStruct::new();
}
```

The compiler complains about `&instance.beep_buffer` not living long enough (as per `'t`). It is clear that my Rust skills are lacking; but can I be pointed in the right direction? What is the correct way to have both a `SoundBuffer` and `Sound` referencing it in the same structure?

I have tried boxing the `SoundBuffer` to no avail. If at all possible, I'd like the two to be contained in the same structure.

EDIT: just to make it clear, I do understand that this is *not* an issue with the library. I'm just asking for "best design practices".

**Comment by crumblingstatue** [comment]
This sounds a lot like [this](https://github.com/jeremyletang/rust-sfml/issues/180) issue.

In a nutshell, Rust doesn't have good support for self-referential structs at the moment.

For now, I would recommend finding a different design than having a borrowed and its borrower in the same struct.

**Comment by aszkid** [comment]
That makes sense, thank you very much!
