### ISSUE TITLE
do you support RTL languages like Arabic?

### ISSUE THREAD

**Issue by adals** [jeremyletang/rust-sfml#186]
do you support RTL languages like Arabic? if you dont how can I implement your library with other libraries like
https://github.com/servo/unicode-bidi

thanks

**Comment by crumblingstatue** [comment]
If I understand correctly, SFML itself doesn't support RTL, so there is not much I can do.
Reference: https://github.com/SFML/SFML/issues/246

**Comment by crumblingstatue** [comment]
Since upstream doesn't support this, there isn't anything we can do. Closing.
