### ISSUE TITLE
Handling lifetimes when drawing VertexArray with Texture

### ISSUE THREAD

**Issue by vangroan** [jeremyletang/rust-sfml#187]
I am unsure how to implement a custom entity using `VertexArray` and `Texture` (for a tilemap, as per the [SFML docs](https://www.sfml-dev.org/tutorials/2.4/graphics-vertex-array.php#example-tile-map)), but am unable to find an appropriate example.

My custom entity owns its `VertextArray` and borrows the `Texture` from the outer Resources container, however when `RenderStates` borrows the reference the lifetime requirements conflict.

```rust
pub struct CustomEntity<'s> {
    array: VertexArray,
    texture: &'s Texture,
}

impl<'s> Drawable for CustomEntity<'s> {
    fn draw<'a: 'shader, 'texture, 'shader, 'shader_texture>(
        &'a self,
        render_target: &mut RenderTarget,
        states: RenderStates<'texture, 'shader, 'shader_texture>,
    ) {
        states.texture = Some(&self.texture);
        render_target.draw_with_renderstates(&self.array, states);
    }
}
```

Obviously this won't work because the lifetimes `'s` and `'texture`  are distinct.

```
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter in function call due to conflicting requirements
   |
64 |         states.texture = Some(&self.texture);
   |                               ^^^^^^^^^^^^^
   |
```

What would the appropriate usage then be?

**Comment by crumblingstatue** [comment]
The whole `Drawable` system in rust-sfml is kind of a mess, as you can see from the sheer number of lifetimes. If you can, avoid it, and use `RenderTarget::draw` directly, when possible.

Anyway, it seems like `'a` should also outlive `'texture`, not just `'shader` (`'a: 'shader + 'texture`), so I fixed that on [this branch](https://github.com/jeremyletang/rust-sfml/compare/drawable-texture-lifetime). Can you test it out, and see if it works? You can depend on that branch like this:

```toml
[dependencies.sfml]
git = "https://github.com/jeremyletang/rust-sfml.git"
branch = "drawable-texture-lifetime"
```

**Comment by vangroan** [comment]
Thank you for this. I went with your suggested solution of using my own `draw`, and it's working for the tilemap case. I'm also passing through a Transform down the `draw` calls of game objects, which appears to be working well enough.

I understand that lifetimes get out of hand very quickly, and bubble up the API. My own game code got bonkers verbose the moment I made my message passing and game context polymorphic.

PS: Thanks for the Sprite tip. That's good to know when doing trees and walls. 👍

**Comment by twetzel59** [comment]
I'm afraid that might be the case...

In my game I'm using a reference counting hack. Essentially, I link to the csfml_*_sys crates and use the native method to set a ``Sprite``'s texture to one in a ``Rc<Texture>``. However, this requires extreme diligence, as it violates Rust's safety guarantees.

**Comment by crumblingstatue** [comment]
VertexArray is gone now, so I'm closing this.
The recommended way to draw vertex arrays is to have a Vec<Vertex> and use RenderTarget::draw_primitives.
See the `spritebench` example.
