### ISSUE TITLE
Static Linking?

### ISSUE THREAD

**Issue by kaikalii** [jeremyletang/rust-sfml#188]
When I used SFML with C++, I was able to use CMake to build a static version of the library, and I could link against it with the -DSFML g++ compiler flag. Is there a way to allow for static linking with rust-sfml so that compiled executables do not require the .dll files be in the same directory?

**Comment by crumblingstatue** [comment]
As far as I understand, C++ does not mix well with other languages when linking statically, so this isn't possible in a sane manner.

References:
- https://github.com/SFML/CSFML/issues/18
- https://en.sfml-dev.org/forums/index.php?topic=13908.0

I played around with trying to make it work after I read your request, but I just keep getting link errors.

I might be wrong, and it's possible. Feel free to send a pull request if you know how to achieve this.

**Comment by crumblingstatue** [comment]
I'm closing this since I don't  think it's possible.

**Comment by crumblingstatue** [comment]
Might be possible using a c++ linker, which would have to be configured to link your rust project. I might look into this.
