### ISSUE TITLE
Unsafe ConvexShape method

### ISSUE THREAD

**Issue by twetzel59** [jeremyletang/rust-sfml#190]
Hello,

The ``set_point`` method in ``graphics::ConvexShape`` should technically be marked as unsafe, as it does not bounds check. This may not be practical, but it is worth reporting. :)

**Comment by crumblingstatue** [comment]
Good catch!

This should probably be fixed by adding bounds checking on the Rust side, unless someone actually needs an unchecked version for raw performance. In that case, there could be a separate unsafe unchecked variant.

**Comment by twetzel59** [comment]
Agree on both points!
