### ISSUE TITLE
Updating crates.io crate

### ISSUE THREAD

**Issue by comfix** [jeremyletang/rust-sfml#206]
Could you update the crates available on crates.io / lib.rs to use the current source of the repository?

Crates.io still holds version 0.14.0 which is using SFML 2.4

**Comment by crumblingstatue** [comment]
I wanted to finish fully updating the API to match SFML 2.5 before I release a new version, but I've been feeling uninspired lately, so I never got to it.

I'll do a quick sanity checkup then release a new version. I guess there is no real harm in doing so.

**Comment by crumblingstatue** [comment]
This is now done, sorry for the delay.
