### ISSUE TITLE
Issue implementing ResourceHolder from SFML Game Dev book

### ISSUE THREAD

**Issue by Tyrendel** [jeremyletang/rust-sfml#209]
I'm trying to implement ResourceHolder from SFML Game Dev book: the idea is to manage resources (fonts, textures, sounds, …) in a single generic Class using a HashMap<Id, Resource> but I'm stuck:
- functions Resource::from_file(file_name) return SfBox<Resource> from which I haven't been able to find a way to get ownership over loaded Resource (can't use * because Clone isn't implemented)
- SfBox can only contain objects implementing Dispose Trait which is a private trait
-> I can't use Box in the generic ResourceHolder structure because I can't move resources from SbBox to a Box, and I can't use SfBox because I can't specify that the generic type has to implement Dispose trait SfBox requires

Am I missing something or is it really impossible to implement this kind of generic behaviour
yet? If so is there any plan to make this possible?

**Comment by crumblingstatue** [comment]
I see how the `Dispose` trait not being available can be an issue. I'll see how I can best solve this.

**Comment by crumblingstatue** [comment]
Upon further investigation, `Dispose` isn't the only thing that prevents implementing a generic resource holder. The types would also need to be able to load from file in a generic way. Right now, `from_file` is an inherent method on each type, not a trait method. I'm not sure if adding a trait for this would be worth the complexity. This needs further thought and investigation.

**Comment by crumblingstatue** [comment]
I've given this further thought, and I retract my previous statement. The only thing we need to allow is `SfBox` to be used in a generic context, the rest can actually be written by the user.

So I went ahead and [added a public trait that you can now satisfy `SfBox`'s requirements with](https://github.com/jeremyletang/rust-sfml/commit/12306322204861aea8a8567fd84c9615531b6046).

Let me know how it works out for you!

**Comment by Tyrendel** [comment]
Thanks for the quick update!

I followed the wiki steps on a new project and had the resource-holder example run successfully, however I don't get how to switch from crate.io sfml 0.15.1 to the git master branch… Can you help and share a link?

**Comment by crumblingstatue** [comment]
To use the git master branch, you can declare your dependency like this
```toml
[dependencies.sfml]
git = "https://github.com/jeremyletang/rust-sfml.git"
```

**Comment by Tyrendel** [comment]
It's working great, thanks!
