### ISSUE TITLE
Context getFunction

### ISSUE THREAD

**Issue by DoctorVWA** [jeremyletang/rust-sfml#211]
Hello.

Looks like the binding doesn't have the following method for the Context from the C++ lib: [getFunction](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Context.php#a998980d311effdf6223ce40d934c23c3), I was trying to implement imgui with the SFML package and came across [this rust crate](https://github.com/michaelfairley/rust-imgui-opengl-renderer), which supports opengl rendering for imgui, and should be compatible with all OpenGL based rendering libs, so I wondered if there was a way of using it in sfml-rust, and, since the crate still only for opengl 3+, I wasn't able to test it, and didn't saw an obvious way of doing that, so I asked this [issue](https://github.com/michaelfairley/rust-imgui-opengl-renderer/issues/10), as michael pointed out, I gonna need this getFunction method in the opengl Context, to use the crate.

Is there a specific reason why it isn't in the crate? Like I mentionated this [milestone](https://github.com/jeremyletang/rust-sfml/issues/142), your idea was to add everything from the docs, including the Context and it's methods. Maybe you just forget about it and it was never too used for everyone in first place, or you just wasn't able to add this to the binding?

Thanks for now. Awaiting a reply.

**Comment by crumblingstatue** [comment]
Unfortunately, this function doesn't seem exposed by [CSFML](https://github.com/SFML/CSFML), so there is not much we can do on the rust-sfml side.

Perhaps if this is important for you, you could try having it added to CSFML.

**Comment by DoctorVWA** [comment]
Thanks for the quick reply, I see you have this [issue](https://github.com/jeremyletang/rust-sfml/issues/194) here, where you delayed the direct SFML implementation and have problems, I guess that's why you use CSFML, I wonder why that isn't implemented there, anyway, really appreciate your help, and thanks for clarifying the things for me, I'll try to do this and come back to here, for now I'll close the issue. Bye :)
