### ISSUE TITLE
Mp3 support?

### ISSUE THREAD

**Issue by heretic13** [jeremyletang/rust-sfml#212]
Hello.
How do you look about mp3 support in your project (maybe optional feature).
I know that mp3 is not officially supported in the sfml project.

Discussion: https://github.com/SFML/SFML/issues/1232
Possible implementation: https://github.com/SFML/SFML/wiki/Source:-MP3-Player

If I use C ++, I take this implementation. But I do not understand what to do if I use rust.

**Comment by crumblingstatue** [comment]
It should be possible with a custom [`SoundStream`](https://docs.rs/sfml/0.15.1/sfml/audio/trait.SoundStream.html), and a [crate that can decode mp3](https://crates.io/search?q=mp3%20decoder). You can play your custom sound streams with [`SoundStreamPlayer`](https://docs.rs/sfml/0.15.1/sfml/audio/struct.SoundStreamPlayer.html).

Here is an example implementation of a mod stream I made a while ago: https://github.com/crumblingstatue/rust-sfml-modstream

**Comment by heretic13** [comment]
Thanks.
Good starting point. 
Now I will explore the sources / examples.
