### ISSUE TITLE
Support for changing the mouse cursor?

### ISSUE THREAD

**Issue by Tru-Dev** [jeremyletang/rust-sfml#217]
Hello!
I have been using this library, and I gotta admit, it's better than SDL.
However, I have been making an implementation of [`iced`](https://github.com/hecrj/iced), and noticed the lack of support for mouse cursors. I searched it up, and SFML proper does support it.
Thanks!

**Comment by crumblingstatue** [comment]
I added experimental support in https://github.com/jeremyletang/rust-sfml/commit/b8cdcfdbae185ce699036c248a76a56d3c1885ab.

Feel free to give it a try!

**Comment by crumblingstatue** [comment]
I think the API I added should be sufficient, so I'm going to close this issue.
