### ISSUE TITLE
Doubled-up lifetime variable name in Drawable::draw

### ISSUE THREAD

**Issue by Ben-PH** [jeremyletang/rust-sfml#218]
The trait function `Drawable::draw` has the following signature:

```rust
    fn draw<'a: 'shader, 'texture, 'shader, 'shader_texture>(
        &'a self,
        target: &mut dyn RenderTarget,
        states: RenderStates<'texture, 'shader, 'shader_texture>,
    );
```

I might be missing something,  but does `'a` need to be subtyped for `'shader` twice? If not, this should be removed so the code is better self-documenting purposes. If it can't be changed, perhaps a doc-comment to explain why the second `'shader` is required.

Lifetimes are one of the biggest sources of frustration for people new to the language. Getting an API's lifetime as simple and well-documented as possible is especially important.

**Comment by crumblingstatue** [comment]
I don't see it being subtyped twice in that code, only once. The other 'shader is the actual declaration of that lifetime parameter.

**Comment by crumblingstatue** [comment]
Since I don't think there are any doubled lifetimes here, I'm gonna close this issue. Feel free to reopen it if you think otherwise.
