### ISSUE TITLE
[Question] loading sRGB textures

### ISSUE THREAD

**Issue by silverweed** [jeremyletang/rust-sfml#219]
I cannot figure out how you're supposed to load an sRGB texture from disk (or memory, or image).
In SFML, you would do:

```c++
sf::Texture texture;
texture.setSrgb(true);
texture.loadFromFile(...);
```

But in rust-sfml this is not possible as `from_file` (and all the `from_` functions) are static.  Am I missing something here? 

Edit: I peeked into the CSFML API and apparently it's more of a CSFML issue, as the loadFrom* functions are not exposed for some reason, so I'm gonna open this issue in the CSFML repo.

**Comment by crumblingstatue** [comment]
Yep, looks like we'll have to wait until CSFML exposes the necessary APIs.

I still kinda wanna bind directly to SFML to avoid issues like this, but that will probably not come for a long time.

**Comment by crumblingstatue** [comment]
We now vendor CSFML, so this issue could be tackled completely by us now. I'll definitely investigate soon.

**Comment by crumblingstatue** [comment]
As of https://github.com/jeremyletang/rust-sfml/commit/01ee40413233197953aeb7c5fb50ad1447e296ab, this has been implemented!
