### ISSUE TITLE
Add constructor for Sprite that takes a Texture and an IntRect.

### ISSUE THREAD

**Issue by pjfordham** [jeremyletang/rust-sfml#221]

**Comment by crumblingstatue** [comment]
Would `with_texture_and_rect(&Texture, &IntRect)` be satisfactory?

**Comment by pjfordham** [comment]
Yeah, that's just what I want.

thanks,

-Pete

**Comment by crumblingstatue** [comment]
Added in c5108ccff10402d8e2bd70a0a1992afd2131404f
