### ISSUE TITLE
Question: How to open opengl inside sfml window with rust

### ISSUE THREAD

**Issue by mrutyunjayan** [jeremyletang/rust-sfml#223]
I was just wondering how I can use opengl within rust-sfml...with cpp I could include the sfml/opengl.hpp header but I can't find documentation on how to do it with rust.

**Comment by mrutyunjayan** [comment]
Specifically, my question is about using things like load the OpenGL function pointers

**Comment by crumblingstatue** [comment]
I don't know how well this is supported, I personally never used OpenGL with SFML, so I can't answer this question.

**Comment by crumblingstatue** [comment]
We now have an [OpenGL example](https://github.com/jeremyletang/rust-sfml/blob/master/examples/opengl.rs)!
