### ISSUE TITLE
From<Vector<_>> for Vector<_> structs

### ISSUE THREAD

**Issue by aleokdev** [jeremyletang/rust-sfml#230]
Implement From<Vector<_>> for each vector type so that it is possible to do i.e. `Vector2f::from(vec)`. I keep writing `Vector2f { x: vec.x as f32, y: vec.y as f32 }` to convert from integer to float vectors and it's a pain.

**Comment by dogunbound** [comment]
https://github.com/jeremyletang/rust-sfml/pull/265

This feature is now implemented with generic functions. You may have to directly reference the github in your cargo.toml for this feature.

**Comment by crumblingstatue** [comment]
This has been implemented with dedicated methods [`into_other`](https://docs.rs/sfml/latest/sfml/system/struct.Vector2.html#method.into_other), `try_into_other`, and `as_other`
