### ISSUE TITLE
Mark constructors for Time, Vector2, Vector3 as const

### ISSUE THREAD

**Issue by Kolsky** [jeremyletang/rust-sfml#232]

**Comment by crumblingstatue** [comment]
Vector2 and Vector3 new methods are already const on git master.
Time is more difficult because it's an opaque type and the constructors call into FFI.

**Comment by crumblingstatue** [comment]
Time::microseconds and Time::milliseconds are const fn, but making Time::seconds const fn isn't possible right now, because of https://github.com/rust-lang/rust/issues/57241

**Comment by crumblingstatue** [comment]
I think these are now as reasonably const as possible, so I'm closing this.

**Comment by crumblingstatue** [comment]
Just as an update, now that Rust 1.82 supports `const fn` floating point arithmetic, `Time::new` is now also const.
