### ISSUE TITLE
Cant find VertexBuffer on 0.15.1 installation

### ISSUE THREAD

**Issue by jcbritobr** [jeremyletang/rust-sfml#234]
Win 10 pro x64, 
Rust 1.51 msvc toolchein

I installed sfml 0.15.1 but it lacks VertexBuffer implementation. Looked in github and there is a module. May be a problem with the package in crates.io?

**Comment by crumblingstatue** [comment]
Right now it's only in the git version, but I think it's about time I published a new version. I'll take a look today and try to publish 0.16

**Comment by crumblingstatue** [comment]
[0.16.0 is now released!](https://github.com/jeremyletang/rust-sfml/releases/tag/v0.16.0)
