### ISSUE TITLE
Vendor CSFML

### ISSUE THREAD

**Issue by crumblingstatue** [jeremyletang/rust-sfml#236]
CSFML could be vendored in the rust-sfml repo, and customly tailored to work better with rust-sfml. It would also allow us not to have to wait on a new CSFML release for any bugfixes, allowing us to control new rust-sfml releases better.

I'm going to be experimenting with this over the next few days, but I would like to hear feedback if anyone has any.

The experimental branch can be found here: https://github.com/jeremyletang/rust-sfml/tree/vendored-csfml

# Progress report 1
I have been doing some experimenting, but it's going to be difficult to do this.
- CSFML cannot be reliably linked statically (See #188)
- CMake has to be introduced as a build dependency
- SFML header files are required to build CSFML
- Possibly more problems

# Progress report 2
The biggest hurdle for static linking is reliably linking in the C++ standard library. The most reliable way I've found is `-lstdc++` at the very end of the dependency chain. But I imagine that doesn't work for MSVC and other compilers that don't support the GCC-like options.
I tried to make a `libstdc++`-less wrapper, but that's basically impossible because operators  new/delete are defined in the standard library as well.

The most reliable thing seems to be to produce dynamic libs. It's a pain because more artifacts will have to be shipped with the produced binary.

# Progress report 3
We're now using the [link-cplusplus](https://crates.io/crates/link-cplusplus) crate to link C++ standard library and still link statically to CSFML (now called rcsfml to distinguish it from upstream). Further testing is required to confirm it works in most scenarios.

**Comment by crumblingstatue** [comment]
Ref #235

**Comment by jcbritobr** [comment]
I whould like to test it when its available.

**Comment by crumblingstatue** [comment]
I have been doing some experimenting, but it's going to be difficult to do this.
- CSFML cannot be reliably linked statically (See #188)
- CMake has to be introduced as a build dependency
- SFML header files are required to build CSFML
- Possibly more problems

**Comment by crumblingstatue** [comment]
Here is a very experimental branch if anyone wants to give it a try and give feedback: https://github.com/jeremyletang/rust-sfml/tree/vendored-csfml

**Comment by jcbritobr** [comment]
> 
> 
> Here is a very experimental branch if anyone wants to give it a try and give feedback: https://github.com/jeremyletang/rust-sfml/tree/vendored-csfml

I'll test it.

**Comment by crumblingstatue** [comment]
CSFML is now vendored. Please report any issues you may encounter.
