### ISSUE TITLE
Travis build no longer functional

### ISSUE THREAD

**Issue by palfrey** [jeremyletang/rust-sfml#241]
https://travis-ci.org/github/jeremyletang/rust-sfml doesn't appear to be working and https://travis-ci.com/github/jeremyletang/rust-sfml isn't activated

**Comment by crumblingstatue** [comment]
It might be time to switch to GitHub Actions, as Travis CI seems to be dying.

**Comment by crumblingstatue** [comment]
rust-sfml now uses Github Actions for CI
