### ISSUE TITLE
segfault on geometry shader creation

### ISSUE THREAD

**Issue by Tyrendel** [jeremyletang/rust-sfml#245]
Hi,

I've got a segfault when trying to create a geometry shader from file or from memory, on Windows and Mac.

Minimal example:
```
extern crate sfml;
fn main() {
    sfml::graphics::Shader::from_memory(None, Some("test"), None);
}
```

> Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by Tyrendel** [comment]
It seems from CSFML source that it isn't expected to load a geometry shader without also loading a vertex and a fragment shader. It works well that way. As I'm just starting to learn about geometry shaders I suspect it is indeed meaningless to try to load only a geometry shader…

**Comment by crumblingstatue** [comment]
Ideally rust-sfml shouldn't segfault in safe code, so I'm reopening this issue for investigation

**Comment by crumblingstatue** [comment]
Hi, I made this commit: https://github.com/jeremyletang/rust-sfml/commit/7d7dafce8621973ca97dbd17fc2f6b02158a6df0

If you'd like, you can test it and see if it fixes the crash.

**Comment by Tyrendel** [comment]
I can't seem to compile this revision :
sfml = { git = "https://github.com/jeremyletang/rust-sfml.git", rev = "7d7dafce8621973ca97dbd17fc2f6b02158a6df0" }

```
error: failed to run custom build command for `sfml v0.16.0 (https://github.com/jeremyletang/rust-sfml.git?rev=7d7dafce8621973ca97dbd17fc2f6b02158a6df0#7d7dafce)`

Caused by:
  process didn't exit successfully: `C:\Users\othomass\IdeaProjects\test_sfml_fix\target\debug\build\sfml-2bb26d023be6b2aa\build-script-build` (exit code: 1)
  --- stderr


  error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-I" "CSFML/src/" "-I" "CSFML/include/" "-W4" "-DCSFML_SYSTEM_EXPORTS" "-DCSFML_AUDIO_EXPORTS" "-DCSFML_WINDOW_EXPORTS" "-DCSFML_GRAPHICS_EXPORTS" "-FoC:\\Users\\othomass\\IdeaProjects\\test_sfml_fix\\target\\debug\\build\\sfml-e3cb76aaef7670a8\\out\\CSFML/src/System/Clock.o" "-c" "CSFML/src/System/Clock.cpp" with args "cl.exe" did not execute successfully (status code exit code: 2).
```

I can compile with those dependency without pbl appart from the function existing or not:
sfml = "0.15.1"
sfml = "0.16.0"
sfml = { git = "https://github.com/jeremyletang/rust-sfml.git", rev = "a94399f9118636b551ba1a9eb2f69dcd29d2cfa0" }

So I must be missing something...

**Comment by crumblingstatue** [comment]
This should be fixed in the latest version.
