### ISSUE TITLE
Make RenderState.repr.transform public again or add getters

### ISSUE THREAD

**Issue by Tyrendel** [jeremyletang/rust-sfml#258]
In rust-sfml 0.15.1 I used to manage my `RenderStates` working on the transform directly :
`renderstate.transform.scale_with_center(...)`

In rust-sfml 0.16.0 I see the transform matrix has been moved to a `repr` member of `RenderStates` but it is private and no getter is available. Am I missing the "correct" way to manage `RenderStates` ?

**Comment by crumblingstatue** [comment]
Thank you for voicing your concern. Currently I'm unable to work on rust-sfml, but I'll get back to reviewing this in a week or so at most

**Comment by crumblingstatue** [comment]
I made [both blend_mode and transform public again](https://github.com/jeremyletang/rust-sfml/commit/832cfaa7df3806af1598b5a0a06ae05da23950a4).

**Comment by Tyrendel** [comment]
Great, thanks, I’ll try it as soon as I manage to build with the vendored CSMFL!

**Comment by crumblingstatue** [comment]
New version of rust-sfml is out with this fixed.
