### ISSUE TITLE
[Question] SFML package requirement?

### ISSUE THREAD

**Issue by alexdevteam** [jeremyletang/rust-sfml#259]
Even after #242, CSFML and SFML are required as packages in the system for the crate to build.

The current requirements (for the master build) are not very precise. What exactly is vendored by this crate, and why is SFML still required on the building system?

**Comment by bjorn** [comment]
Hmm, likely I needed to install those because I used the latest release, and that change isn't in 0.16 yet.

**Comment by crumblingstatue** [comment]
Latest release (0.16) requires both SFML and CSFML.
The git master version requires only SFML. CSFML is vendored. This however also means that a C++ compiler is required to build the project, as well as libclang for binding generation purposes.
