### ISSUE TITLE
Fonts loaded from memory require the source data buffer to be kept available

### ISSUE THREAD

**Issue by cpardotortosa** [jeremyletang/rust-sfml#261]
There is a warning about this on [sfml documentation](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Font.php#abf2f8d6de31eb4e1db02e061c323e346)

When using this with rust, the font does not work if the buffer is dropped. This should be in the documentation.

**Comment by crumblingstatue** [comment]
I think for the time being I'll make from_memory unsafe and document the behavior.
It would pollute the Font/Text APIs with lifetimes to fix this more thoroughly, which I don't have motivation for right now.

**Comment by crumblingstatue** [comment]
I created https://github.com/jeremyletang/rust-sfml/commit/7cc48d5781cacf85f31aa65a0b79eced5da3941f to address this.

**Comment by crumblingstatue** [comment]
I also added a safe variant in fc390c82a4f276aa9d0d895fdf8a7d494035139e that requires `'static`.
I think that's sufficient to address this issue.
