### ISSUE TITLE
Upload alpha version to crates.io

### ISSUE THREAD

**Issue by aleokdev** [jeremyletang/rust-sfml#280]
I believe uploading a pre-release version of the current main branch to crates.io would greatly help users of the crate. I imagine there hasn't been a version uploaded for a while because CSFML is now being bundled with the crate. However, if we mark the version as an "alpha", it'd alert users that the version may not be entirely stable while helping other libraries or advanced users such as me to work with the crate without relying on the GitHub repository and specific commits.

**Comment by crumblingstatue** [comment]
I'll try to make a release tomorrow.

**Comment by dogunbound** [comment]
I agree. For the most part, looking through the docs is synced with the main repo, but every now and then I have to scroll through the source code to figure out what's going on. This would be greatly appreciated.

**Comment by crumblingstatue** [comment]
I don't think releasing a new version after every commit/PR is a good idea. That would be very spammy

**Comment by crumblingstatue** [comment]
I'm working on removing dependency on bindgen before I publish a new version.

If all goes well, I can publish a new version tomorrow.

**Comment by crumblingstatue** [comment]
[0.17](https://github.com/jeremyletang/rust-sfml/releases/tag/v0.17.0) has been published!
