### ISSUE TITLE
Reason for refcounted views?

### ISSUE THREAD

**Issue by aepsil0n** [jeremyletang/rust-sfml#31]
In `rsfml::graphics::RenderWindow` all the methods dealing with views (`set_view`, `get_view` …) deal with Rc<RefCell<View>> objects in their instances. I wonder why this is. It feels a bit bloated to deal with these objects instead of simple borrowed pointers. So in essence my question is the following: why should the RenderWindow care at all about how the view's memory is managed?

Simply want to understand your rationale behind this.

**Comment by crumblingstatue** [comment]
I don't think this applies anymore. `Rc` is nowhere to be found in the `render_window` module anymore.
