### ISSUE TITLE
Fatal SYNTAX ERROR while compiling with SFML 2.6. 

### ISSUE THREAD

**Issue by GrimReaper420** [jeremyletang/rust-sfml#310]
From 2.5 to 2.6, SFML removed the sf::Window class declaration from the touch.hpp header (see here https://github.com/SFML/SFML/commit/ae337952a98bfb71d228221015c947df94bdd6b4#diff-b1dab56b9bd27dcc4b41fd0b14410981df77c0639d76eb7d70c750c79bf8f5f9). 

When building the touch.cpp of rust-sfml v0.20.0 file while using SFML 2.6 headers this causes a syntax error.:

>  CSFML/src/Window/Touch.cpp(13): error C2039: **'Window': is not a member of 'sf'**
  C:\Program Files (x86)\SFML\include\SFML/Window/Touch.hpp(35): note: see declaration of 'sf'
  CSFML/src/Window/Touch.cpp(13): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
  CSFML/src/Window/Touch.cpp(13): error C2143: **syntax error: missing ',' before '*'**
  CSFML/src/Window/Touch.cpp(14): error C2065: 'relativeTo': undeclared identifier
  exit code: 2

**Steps to reproduce:**

1. compile v0.20.0 of rust-sfml using SFML 2.6.x headers

**Suggested fix:** 

The master branch of rust-sfml compiles correctly due to: https://github.com/jeremyletang/rust-sfml/commit/14d9bc2b07af1e342506adeecbacedb16e0e9ba2
So create a new release (0.21.0) of rust-sfml with the current master branch to fix compatibility with SFML 2.6.x.

Thank you.

**Comment by crumblingstatue** [comment]
I released 0.21.0. Let me know if you have any issues with it!

**Comment by GrimReaper420** [comment]
It works perfectly! Thanks.

**Comment by GrimReaper420** [comment]
Closing.
