### ISSUE TITLE
Window Border in Windows 

### ISSUE THREAD

**Issue by Noxivs** [jeremyletang/rust-sfml#37]
Hi,
It's me again. I'm glad that sfml works properly on windows seven but the border window  of the example is like a windows 98 (aero theme not loaded ?). We're in 2014, and i hope you know how i can forget this old border...

Regards.

**Comment by crumblingstatue** [comment]
With rust-lang/rust#13259 fixed, this should be fixed too.
Closing, feel free to reopen if this issue still persists.
