### ISSUE TITLE
Updating a texture from a window takes the window by value

### ISSUE THREAD

**Issue by Bastacyclop** [jeremyletang/rust-sfml#74]
Hi,
I wanted to make a pause screen for a game, so I thought I would update a snapshot texture from the window and then draw it, but the [update_from_window](https://github.com/jeremyletang/rust-sfml/blob/c86ab96b9161529216066660a2532d8425cf105f/src/graphics/texture.rs#L212) and [update_from_render_window](https://github.com/jeremyletang/rust-sfml/blob/c86ab96b9161529216066660a2532d8425cf105f/src/graphics/texture.rs#L230) Texture's functions are taking the window by value, so I couldn't use it anymore. Shouldn't them take the window by reference ?

I changed my local copy to use references and it runs fine, but maybe I'm wrong.

**Comment by jeremyletang** [comment]
hi,

yes it's clearly an error, these methods should take the window by reference. I can't change this right now if you want or you can submit a PR ! Just tell me.

**Comment by Bastacyclop** [comment]
I'll submit a PR then :).
I just need to make the changes on a clean pull.

**Comment by jeremyletang** [comment]
fixed by #75
