### ISSUE TITLE
RFC: Rename crate from `rsfml` to `sfml`

### ISSUE THREAD

**Issue by crumblingstatue** [jeremyletang/rust-sfml#80]
The crate is already used in the context of Rust, so the `r` is redundant.
`sfml` is one letter shorter, and more consistent with other bindings like rust-sdl and rust-sdl2,  which use `sdl` and `sdl2` for their crate names respectively.

The only drawback is that existing code would need to be changed to use `sfml` instead of `rsfml`, but that sounds like just a simple search&replace operation.

Alternatively, we could use `sf`, which is even shorter, and in line with the original SFML library, which is contained in the `sf` namespace.

**Comment by jeremyletang** [comment]
Okay. let's do this change.

**Comment by crumblingstatue** [comment]
Implemented in 61685f2c0094def9620f392cf5220b02e23d8f31.
