### ISSUE TITLE
Add crates.io package

### ISSUE THREAD

**Issue by crumblingstatue** [jeremyletang/rust-sfml#82]
Tracking issue for adding rust-sfml as a package to crates.io.

~~Pending on #81.~~

**Comment by jeremyletang** [comment]
I will do this soon (probably tonight), and add you as a maintainer @crumblingstatue if it's always okay for you.

**Comment by crumblingstatue** [comment]
> I will do this soon (probably tonight), and add you as a maintainer @crumblingstatue if it's always okay for you.

Yes, thank you!

**Comment by crumblingstatue** [comment]
I added a link to the documentation in 1fdb61ea691f9e71e156d92ecc78d069d0b2d626, but it's out of date. See #83.

**Comment by jeremyletang** [comment]
done [crates.io](https://crates.io/crates/sfml).
