### ISSUE TITLE
Update online documentation, keep it up to date

### ISSUE THREAD

**Issue by crumblingstatue** [jeremyletang/rust-sfml#83]
The documentation at http://www.rust-sfml.org/doc/rsfml/index.html is out of date.

It should be updated, and it should be kept up to date, preferably through automated means.

**Comment by crumblingstatue** [comment]
If an automated way is not (yet) possible, I can volunteer to keep it up to date, but I need access to the website for that.

**Comment by crumblingstatue** [comment]
The website is also out of date.

**Comment by Ape** [comment]
Yes, please.

**Comment by jeremyletang** [comment]
hey,
The website is heberged on my own server. So i'm not really okay to share the pass.
But i will update it soon.

**Comment by crumblingstatue** [comment]
I see that rust-sfml is already present on rust-ci.
Couldn't we link there for the documentation?

**Comment by crumblingstatue** [comment]
Here is the link to the rust-ci documentation:
http://www.rust-ci.org/jeremyletang/rust-sfml/doc/rsfml/

Although for some reason It's not updating since dc630d0, see #90.

**Comment by crumblingstatue** [comment]
Now linking to https://crates.fyi for documentation.

If the homepage is not to be updated, the link to it next to the GitHub repo description should be removed.

**Comment by crumblingstatue** [comment]
Documentation is now hosted by https://docs.rs.

I'm going to close this, but create a new issue for the webpage still showing outdated information.
