### ISSUE TITLE
Clarify license in Cargo.toml

### ISSUE THREAD

**Issue by crumblingstatue** [jeremyletang/rust-sfml#86]
When I tried to publish an update to crates.io, it complained about missing `license`/`license-file`, and didn't let me publish. So I put a license-file attribute that points to LICENSE.txt, but now the license field on the crates.io page says "non-standard".
Previously, it said "zlib-acknowledgment". Is that the correct license? If so, it should be put in the `license` field of Cargo.toml.

/cc @jeremyletang

**Comment by jeremyletang** [comment]
yes you're write, I had the licence field when i published the crate and forget to push to the repository after.
The licence is the `zlib-acknowledgment`, it's correspond to the licence used by the original `SFML` (Zlib/Png) and `rust-sfml`.

**Comment by crumblingstatue** [comment]
All right, I added `license = "zlib-acknowledgement"` to Cargo.toml and published the package.
