### ISSUE TITLE
refactor transform

### ISSUE THREAD

**Issue by jeremyletang** [jeremyletang/rust-sfml#95]
Transform is implemented in an ugly way for now. We may need to use a slice to replace internal of the structure.

**Comment by SpaceManiac** [comment]
I don't think it's too bad as-is. If you want to access a specific element, the direct fields have the advantage of compile-time checking (`.a12` vs `[1][2]`). It may be worth adding methods with signatures like `(&self) -> &[f32; 9]` or `(&self) -> &[[f32; 3]; 3]` or directly implementing `Index` (plus `mut` variants if desired).

**Comment by crumblingstatue** [comment]
`Transform` now reflects the C++ API as closely as possible. There are no public fields. There are none in the C++ API either.

I'm going to close this. If there are specific problems with the design, new issues can be opened for them.
